# Generated by Django 6.0.1 on 2026-01-21 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cupon_suscripcionnewsletter_pedido_pedidoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('bodeguero', 'Bodeguero'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
