# Generated by Django 6.0.1 on 2026-01-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_perfilusuario_rol_alter_cupon_descuento_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('defectuoso', 'Producto Defectuoso'), ('incorrecto', 'Producto Incorrecto'), ('danado', 'Producto Dañado'), ('no_satisface', 'No Satisface Expectativas'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(help_text='Describe el problema')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('monto_reembolso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='gestion.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
